name: build

on:
  push:
    paths-ignore:
    - LICENSE
    - README.md
  pull_request:
    paths-ignore:
    - LICENSE
    - README.md
  workflow_dispatch:
  schedule:
    - cron: '30 03 01 */3 *' # Artifacts expire every 3 months

jobs:
  build:
    name: build with sm${{ matrix.sm_version }} on ${{ matrix.os_short }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          
        sm_version:
          - "1.8"
          - "1.9"
          - "1.10"
          - "latest"
          
        include:
          - sm_version: latest
            branch: master
            
          - sm_version: "1.8"
            branch: "1.8-dev"
            
          - sm_version: "1.9"
            branch: "1.9-dev"
            
          - sm_version: "1.10"
            branch: "1.10-dev"
            
          - os: ubuntu-latest
            os_short: linux
            
          - os: windows-latest
            os_short: win
            
    steps:
      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          
      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y clang g++-multilib
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          
      - name: Add msbuild to PATH (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Install (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          :: See https://github.com/microsoft/vswhere/wiki/Find-VC
          for /f "usebackq delims=*" %%i in (`vswhere -latest -property installationPath`) do (
            call "%%i"\Common7\Tools\vsdevcmd.bat -arch=x86 -host_arch=x64
          )
          
          :: Loop over all environment variables and make them global.
          for /f "delims== tokens=1,2" %%a in ('set') do (
            echo>>"%GITHUB_ENV%" %%a=%%b
          )
          
      - name: Checking out SourceMod
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.branch }}
          path: sourcemod-${{ matrix.sm_version }}
          submodules: recursive
          
      - name: Checking out MM:Source
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/metamod-source
          ref: ${{ matrix.branch }}
          path: metamod-${{ matrix.sm_version }}
          
      - name: Checking out AMBuild
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/ambuild
          path: ambuild
          
      - name: Setting up Python
        uses: actions/setup-python@v2
        
      - name: Setting up ambuild
        working-directory: ambuild
        run: python setup.py install
          
      - name: Checking out hl2sdk-csgo
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: csgo
          path: hl2sdk-csgo
          
      - name: Checking out hl2sdk-tf2
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: tf2
          path: hl2sdk-tf2
          
      - name: Checking out hl2sdk-css
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: css
          path: hl2sdk-css
          
      - name: Checking out hl2sdk-hl2dm
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: hl2dm
          path: hl2sdk-hl2dm
          
      - name: Checking out hl2sdk-dods
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: dods
          path: hl2sdk-dods
        
      - name: Checking out hl2sdk-l4d2
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: l4d2
          path: hl2sdk-l4d2
          
      - name: Checking out hl2sdk-l4d
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: l4d
          path: hl2sdk-l4d
          
      - name: Checking out own repository
        uses: actions/checkout@v2
        with:
          path: sourcetvmanager
          
      - name: Compiling SourceTV Manager files
        working-directory: sourcetvmanager
        run: |
          mkdir build
          cd build
          python ../configure.py --enable-optimize --sdks=present --sm-path="${{ github.workspace }}/sourcemod-${{ matrix.sm_version }}" --mms-path="${{ github.workspace }}/metamod-${{ matrix.sm_version }}"
          ambuild
          
      - name: Uploading package
        uses: actions/upload-artifact@v2
        with:
          name: sourcetvmanager-sm${{ matrix.sm_version }}-${{ matrix.os_short }}-${{ env.GITHUB_SHA_SHORT }}
          path: sourcetvmanager/build/package
